# -*- coding: utf-8 -*-
"""Model_training (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VfY32SaElxtzOBUwmpCwfEMkhiX2yIYP
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from keras import regularizers, activations
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Activation, Conv2D, MaxPooling2D, GlobalAveragePooling2D

# Commented out IPython magic to ensure Python compatibility.
from keras.utils import np_utils
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from datetime import datetime
from matplotlib import pyplot as plt
# %matplotlib inline

pip install np_utils

# Commented out IPython magic to ensure Python compatibility.
USE_GOOGLE_COLAB = True

if USE_GOOGLE_COLAB:
    from google.colab import drive
    drive.mount('/content/gdrive')

    # change the current working directory
#     %cd gdrive/'My Drive'/US8K
else:
#     %cd US8K

us8k_df = pd.read_pickle("us8k_df.pkl")

us8k_df.head()

modelum = tf.keras.models.Sequential([
    #first_convolution
    tf.keras.layers.Conv2D(16, (3,3), activation='relu', input_shape=(128, 128, 1)),
    tf.keras.layers.MaxPooling2D(2, 2),
    #second_convolution
    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    #third_convolution
    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    #fourth_convolution
    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])
modelum.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
#model.fit(train_generator, batch_size=32,epochs=100)

def init_data_aug():
    train_datagen = ImageDataGenerator(
        featurewise_center=True,
        featurewise_std_normalization=True,
        fill_mode = 'constant',
        cval=-80.0,
        width_shift_range=0.1,
        height_shift_range=0.0)

    val_datagen = ImageDataGenerator(
        featurewise_center=True,
        featurewise_std_normalization=True,
        fill_mode = 'constant',
        cval=-80.0)
    test_datagen = ImageDataGenerator(
        featurewise_center=True,
        featurewise_std_normalization=True,
        fill_mode = 'constant',
        cval=-80.0)

    return train_datagen, val_datagen,test_datagen

def init_model():
    model1 = Sequential()

    #layer-1
    model1.add(Conv2D(filters=16, kernel_size=5, input_shape=(128, 128, 1),
                      kernel_regularizer=regularizers.l2(1e-3)))
    model1.add(MaxPooling2D(pool_size=(2,2), strides=1))
    model1.add(Activation(activations.relu))

    #layer-2
    model1.add(Conv2D(filters=36, kernel_size=4, padding='valid', kernel_regularizer=regularizers.l2(1e-3)))
    model1.add(MaxPooling2D(pool_size=(2,2), strides=2))
    model1.add(Activation(activations.relu))

    #layer-3
    model1.add(Conv2D(filters=48, kernel_size=3, padding='valid'))
    model1.add(Activation(activations.relu))

    model1.add(GlobalAveragePooling2D())

    #layer-4 (1st dense layer)
    model1.add(Dense(60, activation='relu'))
    model1.add(Dropout(0.5))

    #layer-5 (2nd dense layer)
    model1.add(Dense(10, activation='softmax'))


    # compile
    model1.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

    return model1

model = init_model()
model.summary()

def train_test_split(fold_k, data, X_dim=(128, 128, 1)):
    X_train = np.stack(data[data.fold != fold_k].melspectrogram.to_numpy())
    X_test = np.stack(data[data.fold == fold_k].melspectrogram.to_numpy())

    y_train = data[data.fold != fold_k].label.to_numpy()
    y_test = data[data.fold == fold_k].label.to_numpy()

    XX_train = X_train.reshape(X_train.shape[0], *X_dim)
    XX_test = X_test.reshape(X_test.shape[0], *X_dim)

    yy_train = to_categorical(y_train)
    yy_test = to_categorical(y_test)
    print(yy_test)

    return XX_train, XX_test, yy_train, yy_test

def process_fold(fold_k, data, epochs=50, num_batch_size=32):
    # split the data
    X_train, X_test, y_train, y_test = train_test_split(fold_k, data)

    print('LENGTH BEFORE AUGMENTATION',len(X_train))
    # init data augmention
    train_datagen, val_datagen,test_datagen = init_data_aug()

    # fit augmentation
    train_datagen.fit(X_train)
    print('LENGTH AFTER AUGMENTATION',len(X_train))
    val_datagen.fit(X_train)

    test_datagen.fit(X_test)

    # init model
    model = init_model()
    #model=modelum

    # pre-training accuracy
    score = model.evaluate(val_datagen.flow(X_test, y_test, batch_size=num_batch_size), verbose=0)
    print("Pre-training accuracy: %.4f%%\n" % (100 * score[1]))

    # train the model
    start = datetime.now()
    history = model.fit(train_datagen.flow(X_train, y_train, batch_size=num_batch_size),
                        steps_per_epoch=len(X_train) / num_batch_size,
                        epochs=epochs,
                        validation_data=val_datagen.flow(X_test, y_test, batch_size=num_batch_size))
    end = datetime.now()
    print("Training completed in time: ", end - start, '\n')

    #Generate the confusion matrix
    y_pred=model.predict(X_test)



    return history,y_pred,y_test

def show_results(tot_history):
    """Show accuracy and loss graphs for train and test sets."""

    for i, history in enumerate(tot_history):
        print('\n({})'.format(i+1))

        plt.figure(figsize=(15,5))

        plt.subplot(121)
        plt.plot(history.history['accuracy'])
        plt.plot(history.history['val_accuracy'])
        plt.grid(linestyle='--')
        plt.ylabel('Accuracy')
        plt.xlabel('Epoch')
        plt.legend(['train', 'validation'], loc='upper left')

        plt.subplot(122)
        plt.plot(history.history['loss'])
        plt.plot(history.history['val_loss'])
        plt.grid(linestyle='--')
        plt.ylabel('Loss')
        plt.xlabel('Epoch')
        plt.legend(['train', 'validation'], loc='upper left')

        plt.show()

        print('\tMax validation accuracy: %.4f %%' % (np.max(history.history['val_accuracy']) * 100))
        print('\tMin validation loss: %.5f' % np.min(history.history['val_loss']))



"""SELF ADDED SEGMENT"""

# Create CNN model
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Input(shape=(128, 128, 1)))
model.add(tf.keras.layers.Conv2D(32, 3, strides=2, padding='same', activation='relu'))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))
model.add(tf.keras.layers.BatchNormalization())
#model.add(tf.keras.layers.Conv2D(64, 3, padding='same', activation='relu'))
#model.add(tf.keras.layers.BatchNormalization())
#model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))
#model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Conv2D(128, 3, padding='same', activation='relu'))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(256, activation='relu'))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(10, activation='softmax'))

# Compile model
model.compile(
    loss='categorical_crossentropy',
    optimizer=tf.keras.optimizers.RMSprop(),
    metrics=['accuracy'],
)

REPEAT = 1
fold_k=1
history1 = []

for i in range(REPEAT):
    history1 = []
    print('-'*80)
    print("\n({})\n".format(i+1))

    history,y_pred,y_test = process_fold(fold_k, us8k_df, epochs=100)
    history1.append(history)
    show_results(history1)

show_results(history1)

from sklearn.metrics import confusion_matrix
print(y_pred)
y_pred1=np.argmax(y_pred, axis=1)
#print(y_pred1)
y_test1=np.argmax(y_test, axis=1)
cm = confusion_matrix(y_test1, y_pred1)
import seaborn as sns
fig, ax = plt.subplots(figsize=(10,10))         # Sample figsize in inches

ax = sns.heatmap(cm, annot=True, cmap='Blues')

ax.set_title('Seaborn Confusion Matrix with labels\n\n');
ax.set_xlabel('\nPredicted Values')
ax.set_ylabel('Actual Values ');

## Ticket labels - List must be in alphabetical order
ax.xaxis.set_ticklabels(['air condition','horn','children','dog bark','drilling','engine','gun','jackhammer','siren','music'])
ax.yaxis.set_ticklabels(['air condition','horn','children','dog bark','drilling','engine','gun','jackhammer','siren','music'])

## Display the visualization of the Confusion Matrix.
plt.show()
print(cm)

REPEAT = 1
history1 = []

for i in range(REPEAT):
    history1 = []
    print('-'*80)
    print("\n({})\n".format(i+1))

    history,y_pred,y_test = process_fold(2, us8k_df, epochs=50)
    history1.append(history)
    show_results(history1)

